/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Tabla.ProductoDAO;
import Tabla.Tabla_ProductoVO;
import Tabla.ProductoVO;
import Visual.Principal;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author David
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    
    ProductoDAO dao;
    ProductoVO vo = new ProductoVO();
    Tabla_ProductoVO t = new Tabla_ProductoVO();
    Principal ini= new Principal();
    
    int codigo = 0;
    
    public Visual() {
        initComponents();
        
        t.visualizar_ProductoVO(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void limpiar(){
       txtclave.setText("");
       txtnombre.setText("");
       txtconfe.setText("");
       txttaller.setText("");
       txtfecha.setText("");
       txthora.setText("");
       txtcosto.setText("");
       txtruta.setText("");
       codigo = 0;
    }
    
    boolean Valida(JTextField campo){
    if(campo.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Llene los campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
 //javax.swing.JOptionPane.showMessageDialog(this, "Llene los campos vacios");
        return true;
    } 
        return false;
}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        txtconfe = new javax.swing.JTextField();
        txttaller = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txthora = new javax.swing.JTextField();
        txtcosto = new javax.swing.JTextField();
        txtruta = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtfechaT = new javax.swing.JTextField();
        txthoraT = new javax.swing.JTextField();
        txtcostoT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Fondo3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Agregar.setTitle("Agregar Conferencista");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setText("Agregar Nuevo Conferencista");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Clave");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Nombre");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Conferencia");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Taller");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, 20));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Fecha");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Hora");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 40, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Costo Taller");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Foto");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 40, 20));

        txtclave.setEditable(false);
        txtclave.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 140, -1));

        txtconfe.setToolTipText("Tutulo de pelicula");
        jPanel3.add(txtconfe, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 140, -1));

        txttaller.setToolTipText("en minutos");
        txttaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttallerActionPerformed(evt);
            }
        });
        txttaller.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttallerKeyTyped(evt);
            }
        });
        jPanel3.add(txttaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 140, -1));

        txtfecha.setToolTipText("Formato DD/MM/AAAA");
        txtfecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfechaKeyTyped(evt);
            }
        });
        jPanel3.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 140, -1));

        txthora.setToolTipText("Formato 00:00:00");
        txthora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoraActionPerformed(evt);
            }
        });
        txthora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthoraKeyTyped(evt);
            }
        });
        jPanel3.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 140, -1));

        txtcosto.setToolTipText("Solo valores enteros");
        txtcosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostoActionPerformed(evt);
            }
        });
        txtcosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcostoKeyTyped(evt);
            }
        });
        jPanel3.add(txtcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 140, -1));

        txtruta.setEditable(false);
        txtruta.setBackground(new java.awt.Color(204, 204, 255));
        txtruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutaActionPerformed(evt);
            }
        });
        jPanel3.add(txtruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 140, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("Limpiar");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 80, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Cargar");
        jButton1.setToolTipText("No olvides subir foto");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 140, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Agregar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 100, 30));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Modificar");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 120, 30));

        txtnombre.setToolTipText("Nombre Completo");
        jPanel3.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 140, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Fecha Taller");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 90, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Hora Taller");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 90, -1));

        txtfechaT.setToolTipText("Formato DD/MM/AAAA");
        jPanel3.add(txtfechaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 140, -1));

        txthoraT.setToolTipText("Formato 00:00:00");
        jPanel3.add(txthoraT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 140, -1));

        txtcostoT.setToolTipText("Solo valores enteros");
        txtcostoT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcostoTKeyTyped(evt);
            }
        });
        jPanel3.add(txtcostoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 140, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Costo");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo3.jpg"))); // NOI18N
        jPanel3.add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 470));

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar.getContentPane());
        Agregar.getContentPane().setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Conferencistas");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 640, 293));

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 127, 31));

        jButton6.setBackground(new java.awt.Color(0, 102, 153));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setText("Regresar");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 85, 31));

        jButton7.setBackground(new java.awt.Color(0, 102, 153));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setText("Nuevo");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 120, 30));

        jButton8.setBackground(new java.awt.Color(0, 102, 153));
        jButton8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton8.setText("Modificar");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 126, 30));

        jLabel18.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel18.setText("Agregar Conferencista");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 680, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        j.setFileFilter(fil);
        
        int s = j.showOpenDialog(this);
        if(s == JFileChooser.APPROVE_OPTION){
            String ruta = j.getSelectedFile().getAbsolutePath();
            txtruta.setText(ruta);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

                 
       // int clave = Integer.parseInt(txtclave.getText());
        String nombre = txtnombre.getText();
        String conferencia = txtconfe.getText();
        String Taller = txttaller.getText();
        String Fecha = txtfecha.getText();
        String Hora = txthora.getText();
        
        String FechaT = txtfechaT.getText();
        String HoraT = txthoraT.getText();
        float costo = Float.parseFloat(txtcosto.getText());
        float costoT = Float.parseFloat(txtcostoT.getText());
        File ruta = new File(txtruta.getText());
 if(Valida(txtnombre)== false && Valida(txtconfe)== false&& Valida(txttaller)== false && Valida(txtfecha)== false&& Valida(txthora)== false &&Valida(txtfechaT)== false&& Valida(txthoraT)== false&& Valida(txtcosto)== false && Valida(txtcostoT)== false){
        
        this.agregar(ruta,nombre,conferencia,Taller, Fecha,Hora,FechaT,HoraT,costo,costoT);
        t.visualizar_ProductoVO(tabla);
}       
        
        Agregar.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
     //para que aparezca en los cuadros de dialogo de modificar

        int clic = tabla.rowAtPoint(evt.getPoint());
        
        codigo = (int)tabla.getValueAt(clic, 0);
        String nombre = ""+tabla.getValueAt(clic, 2);
        String conferencia = ""+tabla.getValueAt(clic, 3);
        String Taller = ""+tabla.getValueAt(clic, 4);
        String Fecha = ""+tabla.getValueAt(clic, 5);
        String Hora = ""+tabla.getValueAt(clic, 6);
        String FechaT = ""+tabla.getValueAt(clic, 7);
        String HoraT = ""+tabla.getValueAt(clic, 8);
        float Costo = (float) tabla.getValueAt(clic, 9);
        float CostoT = (float) tabla.getValueAt(clic, 10);
        
        
        txtclave.setText(String.valueOf(codigo));
        txtnombre.setText(nombre);
        txtconfe.setText(conferencia);
        txttaller.setText(Taller);
        txtfecha.setText(Fecha);
        txthora.setText(Hora);
        txtfechaT.setText(FechaT);
        txthoraT.setText(HoraT);
        txtcosto.setText(String.valueOf(Costo));
        txtcostoT.setText(String.valueOf(CostoT));
        txtruta.setText("");
        
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int clave = Integer.parseInt(txtclave.getText());
        String nombre = txtnombre.getText();
        String conferencia = txtconfe.getText();
        String Taller = txttaller.getText();
        String Fecha = txtfecha.getText();
        String Hora = txthora.getText();
        String FechaT = txtfechaT.getText();
        String HoraT = txthoraT.getText();
        float costo = Float.parseFloat(txtcosto.getText());
        float costoT = Float.parseFloat(txtcostoT.getText());
        
        File ruta = new File(txtruta.getText());
        
 if(Valida(txtnombre)== false && Valida(txtconfe)== false&& Valida(txttaller)== false && Valida(txtfecha)== false&& Valida(txthora)== false && Valida(txtfechaT)== false&& Valida(txthoraT)== false && Valida(txtcosto)== false&& Valida(txtcostoT)== false&&Valida(txtruta)==false){
     
    if(ruta!=null){
            this.modificar(ruta,nombre,conferencia,Taller, Fecha,Hora,FechaT,HoraT,costo,costoT,clave);
            t.visualizar_ProductoVO(tabla);
            limpiar();
        }else{
            this.modificar2(nombre,conferencia,Taller, Fecha,Hora,FechaT,HoraT,costo,costoT,clave);
            t.visualizar_ProductoVO(tabla);
            limpiar();
        }
    
        
        Agregar.setVisible(false);
}
  
    
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int id = Integer.parseInt(txtclave.getText());
        int a = JOptionPane.showConfirmDialog(null, "Desea eliminar este Conferencista","Mensaje",JOptionPane.OK_CANCEL_OPTION);
        if(a == 0){
            this.eliminar(id);
            limpiar();
        }
        t.visualizar_ProductoVO(tabla);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Principal ini = new Principal();
        ini.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txttallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttallerActionPerformed

    private void txthoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraActionPerformed

    private void txtcostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Agregar.setVisible(true);
        Agregar.setLocation(450,120);
        Agregar.setSize(420,500);
        
        
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Agregar.setVisible(true);
        Agregar.setLocation(450,120);
        Agregar.setSize(420,500);
        jButton2.setEnabled(false);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtfechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechaKeyTyped
      /* char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();*/
    }//GEN-LAST:event_txtfechaKeyTyped

    private void txthoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthoraKeyTyped
       /* char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();*/
    }//GEN-LAST:event_txthoraKeyTyped

    private void txtcostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcostoKeyTyped
         char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_txtcostoKeyTyped

    private void txttallerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttallerKeyTyped
      /*  char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();*/
    }//GEN-LAST:event_txttallerKeyTyped

    private void txtcostoTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcostoTKeyTyped
       char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_txtcostoTKeyTyped

    public void agregar(File ruta, String nombre, String conferencia, String Taller, String Fecha, String Hora,String FechaT, String HoraT, float costo,float costoT){
        ProductoVO vo = new ProductoVO();
        dao = new ProductoDAO();
        
      //  vo.setClave(clave);
        vo.setNombreConferencista(nombre);
        vo.setNombreConferencia(conferencia);
        vo.setNombreTaller(Taller);
        vo.setFechaa(Fecha);
        vo.setHoraa(Hora);
        vo.setFechaT(FechaT);
        vo.setHoraT(HoraT);
        vo.setCosto(costo);
        vo.setCostoT(costoT);
        try{
            byte[] icono = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(icono);
            vo.setFoto(icono);
        }catch(Exception ex){
            vo.setFoto(null);
        }
        dao.Agregar_ProductoVO(vo);
        limpiar();
    }
    
    public void modificar(File ruta, String nombre, String conferencia, String Taller, String Fecha, String Hora,String FechaT, String HoraT, float costo,float costoT, int clave){
        ProductoVO vo = new ProductoVO();
        dao = new ProductoDAO();
        
        
        vo.setNombreConferencista(nombre);
        vo.setNombreConferencia(conferencia);
        vo.setNombreTaller(Taller);
        vo.setFechaa(Fecha);
        vo.setHoraa(Hora);
        vo.setFechaT(FechaT);
        vo.setHoraT(HoraT);
        vo.setCosto(costo);
        vo.setCostoT(costoT);
        vo.setClave(clave);
        try{
            byte[] icono = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(icono);
            vo.setFoto(icono);
        }catch(Exception ex){
            vo.setFoto(null);
        }
        dao.Modificar_ProductoVO(vo);
    }
    
    public void modificar2(String nombre, String conferencia, String Taller, String Fecha, String Hora,String FechaT, String HoraT, float costo,float costoT, int clave){
        ProductoVO vo = new ProductoVO();
        dao = new ProductoDAO();
        
        vo.setNombreConferencista(nombre);
        vo.setNombreConferencia(conferencia);
        vo.setNombreTaller(Taller);
        vo.setFechaa(Fecha);
        vo.setHoraa(Hora);
        vo.setFechaT(FechaT);
        vo.setHoraT(HoraT);
        vo.setCosto(costo);
        vo.setCostoT(costoT);
        vo.setClave(clave);
        
        dao.Modificar_ProductoVO2(vo);
    }
    
    public void eliminar(int id){
        ProductoVO vo = new ProductoVO();
        dao = new ProductoDAO();
        // vo.setClave(codigo);
        int s=Integer.parseInt(txtclave.getText());
        vo.setClave(s);
        dao.Eliminar_ProductoVO(vo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar;
    private javax.swing.JLabel Fondo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtconfe;
    private javax.swing.JTextField txtcosto;
    private javax.swing.JTextField txtcostoT;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtfechaT;
    private javax.swing.JTextField txthora;
    private javax.swing.JTextField txthoraT;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtruta;
    private javax.swing.JTextField txttaller;
    // End of variables declaration//GEN-END:variables

   


   
}
